version: '3'
services:
  redis:
    image: "redis:alpine" 
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    environment:
      redis_host: "redis"
      redis_port: "6379"
      redis_db: 0

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web