version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/keras-complete-rest-api
    networks:
      - model_server
  redis:
    image: "redis:alpine" 
    networks: 
      - model_server

networks:
  model_server: